meteor:
  image: meteor
  # image: martinezko/alpine-meteor:latest
  # build: ./
  ports:
    - 8888:3000
  volumes:
    - './app:/app'
    - './entrypoint:/docker/entrypoint'    
  entrypoint: /docker/entrypoint

#   meteorexample:
#     image: martinezko/alpine-meteor:latest
#     container_name: meteorexample-1
#     hostname: meteor.click
#     restart: always
#     ports:
#       - 127.0.0.1:3000:80
#     environment:
#       APP: meteorexample
#       ROOT_URL: http://meteor.click/
#       # MONGO_URL: mongodb://USERNAME:PASSWORD@172.17.0.1:27017/DATABASE
#       # MONGO_OPLOG_URL: mongodb://USERNAME:PASSWORD@mongo:27017/local
#       # MAIL_URL: smtp://info@meteor.click:PASSWORD@mail.server.net:465/
#       NODE_ENV: production
#       PORT: 80
#       # METEOR_SETTINGS: '' # paste meteor settings.json here in one line!
#       volumes:
#         - './:/app'
#       entrypoint: /app/entrypoint
#     # logging:
#     #   driver: syslog